### ISSUE TITLE
Para Helena

### ISSUE THREAD

**Issue by Pgarri02** [Pgarri02/TFM#1]
hola guapi,
no sé cómo poner las ls y las lgs en el documento teognisespañol.xml ¿Me ayudas porfis?

**Comment by HelenaSabel** [comment]
Hola Patricia!
Por si acaso lo has hecho sola, te he subido un [archivo diferente](https://github.com/Pgarri02/TFM/blob/master/ejemplo/teognisespanol_heb.xml). Puedes venir una tarde a Humanidades y te explico las expresiones que he utilizado.
